format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/access3-2025.08.000-5ae6wtarlzwmoqx2ywms6bezwwcq7lap/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: e7d455676f84c7b0908c38378f546d91
    md5: e90d8f2bea796e96a5c9075c904470fd
