format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/access3-2025.08.000-6l6ximgl5kxsh2jg3kv7tk4ea5oojcrb/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: a12625fdb9315da2982143c60fd49164
    md5: 635cc0addb4ec8957cb89e8f2b1a9717
