format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/access3-2025.08.000-j3bma557vvc5r6pq5zz32gdiho3qlhvm/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: 8311893b09e69796a16682c4f36b9f26
    md5: 2144aec3eb8d79ee94173f4a327c1367
