format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6-WW3:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/access3-2025.08.000-r3flpv4ukmgxcws6ur2vpwxkyz6pdciy/bin/access-om3-MOM6-CICE6-WW3
  hashes:
    binhash: d557a913bf63955c07905ccc426c47aa
    md5: d9dd5bd94a2cb28a358ba666bb390d27
