format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/access3-2025.08.000-wwsajujpomtzi7et4lhugde3uhcfjdra/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: 6720da79cbfd7e288532e79c2a701747
    md5: 5c0c26f0ed8f09aec5d30da33fb20c79
