format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6-WW3-3965e25:
  fullpath: /g/data/ik11/inputs/access-om3/bin/access-om3-MOM6-CICE6-WW3-3965e25
  hashes:
    binhash: 7e82f075b9973133cb94e9a122b87f69
    md5: 54b6ce08150477a14e06f83aa5a55ff1

