format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/access3-2025.08.000-xzdpwm7dz5ktyh3woxosk6uugpxlgmgl/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: 12c355b9a25d87ac6f109b35ecb72561
    md5: 3ea305777299d889f309680e16f22633
