format: yamanifest
version: 1.0
---
work/INPUT/ACCESS-OM2_IC_bfilled_smoothedland.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/ACCESS-OM2_IC_bfilled_smoothedland.nc
  hashes:
    binhash: e02e993ddf76fc2f6711c47509fb7cdc
    md5: 38cd91ac0a9c131b39a057351bec3116
work/INPUT/JRA55do-datm-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/share/2026.01.21/JRA55do-datm-ESMFmesh.nc
  hashes:
    binhash: c0e9a071f20670930d0e117f13399d78
    md5: 0ecb68f878b91b8adc90838e2c413914
work/INPUT/JRA55do-drof-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/share/2026.01.21/JRA55do-drof-ESMFmesh.nc
  hashes:
    binhash: 9f3ee3ce42e776fcbee8026e0c3880f5
    md5: bf62c4e7786ddfbe56d61b3074d5d16d
work/INPUT/RYF.friver.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.friver.1990_1991.nc
  hashes:
    binhash: 7ed1b4267c202eae4e1e1fb7170adfdc
    md5: 06d549192558fc48c43416b1015044bc
work/INPUT/RYF.huss.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.huss.1990_1991.nc
  hashes:
    binhash: be1a71017ed8b5392505b2b013e05343
    md5: 76bce15820d66e4dbd55674072253869
work/INPUT/RYF.licalvf.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.licalvf.1990_1991.nc
  hashes:
    binhash: e7eb183d2b7cdd685bdee810004cf3c9
    md5: 33aba38d6bffb45f9b1ce6240c2cd21a
work/INPUT/RYF.prra.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.prra.1990_1991.nc
  hashes:
    binhash: 1d8af8b1b94d1cf78a3108477d329d06
    md5: 4e1210fa78c124c1537e8ce28584555c
work/INPUT/RYF.prsn.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.prsn.1990_1991.nc
  hashes:
    binhash: 5b9d401daa0c90298d703a3a2dac12b1
    md5: 1fa60bceab287d4059c6a23d5fb18170
work/INPUT/RYF.psl.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.psl.1990_1991.nc
  hashes:
    binhash: e85798bf489561d1eb316a50b170f318
    md5: 40003042b732f70edaf59f302427b213
work/INPUT/RYF.rlds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.rlds.1990_1991.nc
  hashes:
    binhash: 33502887b018dbb288775102c1411d65
    md5: 449ca4bd2d51794204a6ceedc79bad82
work/INPUT/RYF.rsds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.rsds.1990_1991.nc
  hashes:
    binhash: ca831af4d8931736138d04166910b7c4
    md5: 7d8e5270940eaaf5121b72eea736b2cd
work/INPUT/RYF.tas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.tas.1990_1991.nc
  hashes:
    binhash: ae172b9c06fe1b5b2b0a2b78e7de0d17
    md5: 1947327fb37d4d1e7eee3e1804500721
work/INPUT/RYF.uas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.uas.1990_1991.nc
  hashes:
    binhash: 7271b6b617e233932c5e319a63c64bc3
    md5: 74516d793e148d522b2b2f73eb6eb6c7
work/INPUT/RYF.vas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.vas.1990_1991.nc
  hashes:
    binhash: f353a71a014062723ed2b56353932caf
    md5: 30b92b1e409cff9a9900692aa961aba4
work/INPUT/access-om3-8km-ESMFmesh_Charrassin_nocavity_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/access-om3-8km-ESMFmesh_Charrassin_nocavity_cropped.nc
  hashes:
    binhash: 39c203cbe25b86f2bb2d8adbbbaa58c2
    md5: 3e36f72f89f9a61ae4a1ae5a7a1897a9
work/INPUT/access-om3-8km-nomask-ESMFmesh_Charrassin_nocavity_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/access-om3-8km-nomask-ESMFmesh_Charrassin_nocavity_cropped.nc
  hashes:
    binhash: dd7a5c47e3ac0a6d6e5559bf2c3c3b93
    md5: a49b9c9d816f746b1210005ea167fa3a
work/INPUT/access-om3-8km-rof-remap-weights_Charrassin_nocavity_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/access-om3-8km-rof-remap-weights_Charrassin_nocavity_cropped.nc
  hashes:
    binhash: 0748790e158eeefbbb4c9d7ea403ff4e
    md5: 978cc319f1c193f10afa9fdae167138b
work/INPUT/bottom_roughness_Charrassin_nocavity_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/bottom_roughness_Charrassin_nocavity_cropped.nc
  hashes:
    binhash: 18869b06d2df6b53b1b2a8a81923e1b2
    md5: c172360d26674ade54b621f0c23055e9
work/INPUT/diag_rho2.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/diag_rho2.nc
  hashes:
    binhash: 36ef1761b629df34ea5443850b2f18b4
    md5: b8abcb148bb3ef71282d6be4531e491e
work/INPUT/forcing_access_yr2_8km_fill.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/forcing_access_yr2_8km_fill.nc
  hashes:
    binhash: 9f1cce5f9ee771acf098ceb58de7f5dc
    md5: 08ea05256043a07e62a5aea57e0f816d
work/INPUT/kmt_Charrassin_nocavity_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/kmt_Charrassin_nocavity_cropped.nc
  hashes:
    binhash: 1dc131d2544843113023f7118ef9a7a8
    md5: 7ec3d82ea07c77021acf3f1faded52e8
work/INPUT/ocean_hgrid_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/ocean_hgrid_cropped.nc
  hashes:
    binhash: d33f874bec8aea015ae9de1c08f12f8f
    md5: a1876832e039ca9bf761b8c16a08449e
work/INPUT/ocean_vgrid_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/ocean_vgrid_cropped.nc
  hashes:
    binhash: d319d71d04eaa91e9fab04dec49893f8
    md5: 66f71f2b24bd00b1c220787505e0106e
work/INPUT/salt_restore_interpolated_nearest.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/salt_restore_interpolated_nearest.nc
  hashes:
    binhash: d73604715b2dc98e71f9b9146d4719b7
    md5: 62bcbd4638b849e1fada4f4e08dc228c
work/INPUT/tideamp_Charrassin_nocavity_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/tideamp_Charrassin_nocavity_cropped.nc
  hashes:
    binhash: 30f2762faf5cb24f94afccc584c5ec09
    md5: e714813b1e4bd46dff7936cd86b15366
work/INPUT/topog_Charrassin_nocavity_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/topog_Charrassin_nocavity_cropped.nc
  hashes:
    binhash: be6babbe0153baea152d0ad26d35e57f
    md5: 48bd279b3301e9f41f4aa38030f9ee68
