format: yamanifest
version: 1.0
---
work/INPUT/FEMIP_model_median_iron_2016_fillmiss.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/wombat/initial_conditions/share/2021.06.07/FEMIP_model_median_iron_2016_fillmiss.nc
  hashes:
    binhash: f7faffb810e0612d523da6c5ae669db4
    md5: b81d7ee79a6ca30bfd2e6ccc49874267
work/INPUT/GLODAPv2.2016b.NO3_fillmiss.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/wombat/initial_conditions/share/2024.04.02/GLODAPv2.2016b.NO3_fillmiss.nc
  hashes:
    binhash: 88d5d6cb1fc3f709ee473ad9747f9ed2
    md5: c5afb27948688743858ef966be81ec2e
work/INPUT/GLODAPv2.2016b.PI_TCO2_fillmiss.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/wombat/initial_conditions/share/2024.04.02/GLODAPv2.2016b.PI_TCO2_fillmiss.nc
  hashes:
    binhash: 765758579f17ad65b33401d70ccae270
    md5: 0aa9f4a37ff5f01cc180d85305815829
work/INPUT/GLODAPv2.2016b.TAlk_fillmiss.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/wombat/initial_conditions/share/2024.04.02/GLODAPv2.2016b.TAlk_fillmiss.nc
  hashes:
    binhash: 4f23e10845529b52a4cfe13cbe864a24
    md5: b84783902f2bc82711496cca49e78a16
work/INPUT/GLODAPv2.2016b.TCO2_fillmiss.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/wombat/initial_conditions/share/2024.04.02/GLODAPv2.2016b.TCO2_fillmiss.nc
  hashes:
    binhash: 3d35aa452c66bdf78d0ec18607359ceb
    md5: 9f8ba1f96551df518e86e510a765311e
work/INPUT/GLODAPv2.2016b.oxygen_fillmiss.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/wombat/initial_conditions/share/2024.04.02/GLODAPv2.2016b.oxygen_fillmiss.nc
  hashes:
    binhash: 69305dfb06508866f7e9b4ab49b3ae9a
    md5: 1abf34fa578d0a589615d5e9a0e465ac
work/INPUT/JRA55do-datm-ESMFmesh.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-datm-ESMFmesh.nc
  hashes:
    binhash: 3aa7bd11a69390ed8739af63e41462fd
    md5: f583b0fc505afc28f1d7c949a715cccb
work/INPUT/JRA55do-drof-ESMFmesh.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-drof-ESMFmesh.nc
  hashes:
    binhash: fa1322dbc0ab951527b165f8327c7b5b
    md5: 3b46260b8c14d12925cf70f82da6658e
work/INPUT/RYF.friver.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.friver.1990_1991.nc
  hashes:
    binhash: 7ed1b4267c202eae4e1e1fb7170adfdc
    md5: 06d549192558fc48c43416b1015044bc
work/INPUT/RYF.huss.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.huss.1990_1991.nc
  hashes:
    binhash: be1a71017ed8b5392505b2b013e05343
    md5: 76bce15820d66e4dbd55674072253869
work/INPUT/RYF.licalvf.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.licalvf.1990_1991.nc
  hashes:
    binhash: e7eb183d2b7cdd685bdee810004cf3c9
    md5: 33aba38d6bffb45f9b1ce6240c2cd21a
work/INPUT/RYF.prra.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.prra.1990_1991.nc
  hashes:
    binhash: 1d8af8b1b94d1cf78a3108477d329d06
    md5: 4e1210fa78c124c1537e8ce28584555c
work/INPUT/RYF.prsn.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.prsn.1990_1991.nc
  hashes:
    binhash: 5b9d401daa0c90298d703a3a2dac12b1
    md5: 1fa60bceab287d4059c6a23d5fb18170
work/INPUT/RYF.psl.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.psl.1990_1991.nc
  hashes:
    binhash: e85798bf489561d1eb316a50b170f318
    md5: 40003042b732f70edaf59f302427b213
work/INPUT/RYF.rlds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.rlds.1990_1991.nc
  hashes:
    binhash: 33502887b018dbb288775102c1411d65
    md5: 449ca4bd2d51794204a6ceedc79bad82
work/INPUT/RYF.rsds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.rsds.1990_1991.nc
  hashes:
    binhash: ca831af4d8931736138d04166910b7c4
    md5: 7d8e5270940eaaf5121b72eea736b2cd
work/INPUT/RYF.tas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.tas.1990_1991.nc
  hashes:
    binhash: ae172b9c06fe1b5b2b0a2b78e7de0d17
    md5: 1947327fb37d4d1e7eee3e1804500721
work/INPUT/RYF.uas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.uas.1990_1991.nc
  hashes:
    binhash: 7271b6b617e233932c5e319a63c64bc3
    md5: 74516d793e148d522b2b2f73eb6eb6c7
work/INPUT/RYF.vas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.vas.1990_1991.nc
  hashes:
    binhash: f353a71a014062723ed2b56353932caf
    md5: 30b92b1e409cff9a9900692aa961aba4
work/INPUT/SFe_Hamiltonetal2020_monthly_clim.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/wombat/forcing/global.25km/2025.09.29/SFe_Hamiltonetal2020_monthly_clim.nc
  hashes:
    binhash: ebed216794b09570a25a75f419cae22d
    md5: 5818b47e3e4e09bdd7d21ec30e98f706
work/INPUT/access-om3-25km-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/global.25km/2025.09.04/access-om3-25km-ESMFmesh.nc
  hashes:
    binhash: 39654bf6d029a845016c98b8e11b1a20
    md5: fe23759a0a2e99e7b62d5902ec3331e8
work/INPUT/access-om3-25km-nomask-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/global.25km/2025.09.04/access-om3-25km-nomask-ESMFmesh.nc
  hashes:
    binhash: ed99d845464a8e4e846b338fc60a15e4
    md5: ee1487da73ded9d11c3cc009477b3047
work/INPUT/access-om3-25km-rof-remap-weights.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/cmeps/remap_weights/global.25km/2025.09.03/access-om3-25km-rof-remap-weights.nc
  hashes:
    binhash: 21d1b40f07f6f7b1264a818a2425fc32
    md5: bad64e2a35312bb66a412c139543a5a9
work/INPUT/bottom_roughness.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/tidal_external_files/global.25km/2025.09.03/bottom_roughness.nc
  hashes:
    binhash: 4af02df5f147dc8528a1f4657a0de2c4
    md5: 99698827fe5c5129dce971d006e4fdfc
work/INPUT/grid_spec.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/grids/mosaic/share/2024.05.08/grid_spec.nc
  hashes:
    binhash: 2fb8d504904e652a37185852f17dbcd4
    md5: 709268cd891e6f0e827f6de0249f1a3d
work/INPUT/init_ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/wombat/initial_conditions/global.25km/2025.09.29/init_ocean_wombatlite.res.nc
  hashes:
    binhash: e415490f397aec6bae8f142e1528975f
    md5: 31878038be41546c64875d26b7e637ec
work/INPUT/chl_globcolour_monthly_clim.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/chlorophyll/global.25km/2025.11.21/chl_globcolour_monthly_clim.nc
  hashes:
    binhash: c42a775b34ab909b7352381004fad9db
    md5: 269f4492ae65f6ef9dd6e2a59f2bff4b
work/INPUT/kmt.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/cice/grids/global.25km/2025.09.03/kmt.nc
  hashes:
    binhash: 8152c8ce2bb292b6d5399c1b8f01e40c
    md5: 51219455bb690389583fc5fda9a858c7
work/INPUT/ocean_hgrid.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/grids/mosaic/global.25km/2025.09.02/ocean_hgrid.nc
  hashes:
    binhash: fca9384e7595cfcafe6e970d68598a35
    md5: dd9cb78712fedbdd3e5930f7066bcac8
work/INPUT/ocean_mosaic.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/grids/mosaic/global.25km/2025.09.29/ocean_mosaic.nc
  hashes:
    binhash: 473acc8cf3d3c678ebb9bbe26b4da66d
    md5: 48ca097393aa50b6980b7a097f7f27b7
work/INPUT/ocean_vgrid.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/mom/grids/vertical/global.25km/2025.03.12/ocean_vgrid.nc
  hashes:
    binhash: cbc588e29d819ce8898d77760a65e20d
    md5: 66f71f2b24bd00b1c220787505e0106e
work/INPUT/salt_sfc_restore.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/surface_salt_restoring/global.25km/2025.10.24/salt_sfc_restore.nc
  hashes:
    binhash: 07904ddaf9f52342e79d42b2ba4e40c6
    md5: 0e59f79a3da9a989eb9ce854277599f8
work/INPUT/tideamp.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/tidal_external_files/global.25km/2025.09.03/tideamp.nc
  hashes:
    binhash: b91933f5694d0e2c0c1ac0b3bc0fc3f6
    md5: 1aa1db4e7b14f0486d3546b9bc2a035a
work/INPUT/topog.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/grids/global.25km/2025.09.03/topog.nc
  hashes:
    binhash: e10a19fa6d6285987f6b2b59210b2082
    md5: d9dbcb2d4437cfef78e05b78a2089ed5
work/INPUT/woa23_ts_01_mom.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/initial_conditions/global.25km/2025.10.24/woa23_ts_01_mom.nc
  hashes:
    binhash: 2d69410d03d8a39d17dc6e37cd71aa09
    md5: bd9559e8a3dbefa16080d0340b26be12
