format: yamanifest
version: 1.0
---
work/INPUT/JRA55do-datm-ESMFmesh.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-datm-ESMFmesh.nc
  hashes:
    binhash: 3aa7bd11a69390ed8739af63e41462fd
    md5: f583b0fc505afc28f1d7c949a715cccb
work/INPUT/JRA55do-drof-ESMFmesh.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-drof-ESMFmesh.nc
  hashes:
    binhash: fa1322dbc0ab951527b165f8327c7b5b
    md5: 3b46260b8c14d12925cf70f82da6658e
work/INPUT/RYF.friver.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.friver.1990_1991.nc
  hashes:
    binhash: abba207de30541a83d25e24b424cfa87
    md5: fa3a55aeb6706a1b422d096f61a772c1
work/INPUT/RYF.huss.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.huss.1990_1991.nc
  hashes:
    binhash: 1d67d219c6f161051dec204a1842a968
    md5: 6032d514fdfdd2b6a84bdef0a4ac3afe
work/INPUT/RYF.licalvf.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.licalvf.1990_1991.nc
  hashes:
    binhash: 834da0a081e904fdbc892255d1954062
    md5: 6f927702cbc023cc20d3ddd69695f0a0
work/INPUT/RYF.prra.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.prra.1990_1991.nc
  hashes:
    binhash: 7bc006b83a9891d4f9ef39f4d94ffb05
    md5: ac199086106ec4e41506e6082bccb109
work/INPUT/RYF.prsn.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.prsn.1990_1991.nc
  hashes:
    binhash: a57a154152a830ad1ca820ca9487d5ac
    md5: cd076c877c2c5df61615e04d71ed00e0
work/INPUT/RYF.psl.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.psl.1990_1991.nc
  hashes:
    binhash: 420c371361bb677eb87c01255c6e62b3
    md5: 0dfd94a5c3234fd2016dfdd01e84a170
work/INPUT/RYF.rhuss.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.rhuss.1990_1991.nc
  hashes:
    binhash: fe4460b8d68f94df26adc52fb56a0d6a
    md5: 632519955305cb5c19e286b151439fb5
work/INPUT/RYF.rlds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.rlds.1990_1991.nc
  hashes:
    binhash: 07a7fb6f9d2a3aee4081034f0cfc305a
    md5: 0ea83e107ec883c3f39a12b60ff50d8e
work/INPUT/RYF.rsds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.rsds.1990_1991.nc
  hashes:
    binhash: 2d6c41b66024e460fcfe0a1668bfe151
    md5: b74bf123f1e4557368a61732cf24f1c2
work/INPUT/RYF.tas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.tas.1990_1991.nc
  hashes:
    binhash: 2a7a2f9903346123161b91ed8d5fab52
    md5: 06689885f4f2f726b95a2818ab78a20d
work/INPUT/RYF.uas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.uas.1990_1991.nc
  hashes:
    binhash: bfd4876aac0b31e51a18c7724c84d8b1
    md5: 107bf9480f55597655d2d283b6f6b4ff
work/INPUT/RYF.vas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.vas.1990_1991.nc
  hashes:
    binhash: d15ca562e37e82fb2d31657701f0a560
    md5: 88dc8c70338bbc8f5efc48ed0009a99f
work/INPUT/WOA_IC_bfilled_smoothedland.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/WOA_IC_bfilled_smoothedland.nc
  hashes:
    binhash: d329bbacb3c99d02cb802e8e950e5b87
    md5: 7f23826da79f77f99df54495d78ea46a
work/INPUT/access-om3-8km-ESMFmesh_cropped.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/access-om3-8km-ESMFmesh_cropped.nc
  hashes:
    binhash: 71342df00c81cd5946b9b56efbd908f0
    md5: 3c9890eb438dfc2a35017541e547d4ed
work/INPUT/access-om3-8km-nomask-ESMFmesh_cropped.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/access-om3-8km-nomask-ESMFmesh_cropped.nc
  hashes:
    binhash: 955083ce17ed01a2c7f47228d1dc7d50
    md5: 751232a27de1ef02ae97f7e36b34b6a5
work/INPUT/access-om3-8km-rof-remap-weights_cropped.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/access-om3-8km-rof-remap-weights_cropped.nc
  hashes:
    binhash: 807a40ecf02e67d342a35ab3b0fb079e
    md5: 4e2ec7b3494d8145d1a42b31adc14e59
work/INPUT/forcing_access_yr2_8km_fill.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/forcing_access_yr2_8km_fill.nc
  hashes:
    binhash: 4b6a25ba94219b0f0a990fa089fa7ca4
    md5: 99224c9adef929cfa13ff81e055ea69c
work/INPUT/kmt_cropped.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/kmt_cropped.nc
  hashes:
    binhash: 8539604adf102bbc9fe862d6c3440555
    md5: 265a150d3da871c67864548175aa6441
work/INPUT/ocean_hgrid_cropped.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/ocean_hgrid_cropped.nc
  hashes:
    binhash: b981dac8b68d62e6c12aeaa2a4182b58
    md5: a1876832e039ca9bf761b8c16a08449e
work/INPUT/ocean_vgrid_cropped.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/ocean_vgrid_cropped.nc
  hashes:
    binhash: 6b10f9ec68f261ef37f4e9d79df73460
    md5: 66f71f2b24bd00b1c220787505e0106e
work/INPUT/salt_restore_interpolated_nearest.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/salt_restore_interpolated_nearest.nc
  hashes:
    binhash: 970b42aef5c771810c4b9a376713876e
    md5: f7f396a714aede65510f8eec20b9a885
work/INPUT/topog_cropped.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/topog_cropped.nc
  hashes:
    binhash: 9f9b78f3d2e2ec12af63635f86d29ce8
    md5: 416e0aa41fc080db875ed5ce699ab8f7
