format: yamanifest
version: 1.0
---
work/INPUT/JRA55do-datm-ESMFmesh.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-datm-ESMFmesh.nc
  hashes:
    binhash: 3aa7bd11a69390ed8739af63e41462fd
    md5: f583b0fc505afc28f1d7c949a715cccb
work/INPUT/JRA55do-drof-ESMFmesh.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-drof-ESMFmesh.nc
  hashes:
    binhash: fa1322dbc0ab951527b165f8327c7b5b
    md5: 3b46260b8c14d12925cf70f82da6658e
work/INPUT/RYF.friver.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.friver.1990_1991.nc
  hashes:
    binhash: abba207de30541a83d25e24b424cfa87
    md5: fa3a55aeb6706a1b422d096f61a772c1
work/INPUT/RYF.huss.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.huss.1990_1991.nc
  hashes:
    binhash: 1d67d219c6f161051dec204a1842a968
    md5: 6032d514fdfdd2b6a84bdef0a4ac3afe
work/INPUT/RYF.licalvf.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.licalvf.1990_1991.nc
  hashes:
    binhash: 834da0a081e904fdbc892255d1954062
    md5: 6f927702cbc023cc20d3ddd69695f0a0
work/INPUT/RYF.prra.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.prra.1990_1991.nc
  hashes:
    binhash: 7bc006b83a9891d4f9ef39f4d94ffb05
    md5: ac199086106ec4e41506e6082bccb109
work/INPUT/RYF.prsn.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.prsn.1990_1991.nc
  hashes:
    binhash: a57a154152a830ad1ca820ca9487d5ac
    md5: cd076c877c2c5df61615e04d71ed00e0
work/INPUT/RYF.psl.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.psl.1990_1991.nc
  hashes:
    binhash: 420c371361bb677eb87c01255c6e62b3
    md5: 0dfd94a5c3234fd2016dfdd01e84a170
work/INPUT/RYF.rhuss.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.rhuss.1990_1991.nc
  hashes:
    binhash: fe4460b8d68f94df26adc52fb56a0d6a
    md5: 632519955305cb5c19e286b151439fb5
work/INPUT/RYF.rlds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.rlds.1990_1991.nc
  hashes:
    binhash: 07a7fb6f9d2a3aee4081034f0cfc305a
    md5: 0ea83e107ec883c3f39a12b60ff50d8e
work/INPUT/RYF.rsds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.rsds.1990_1991.nc
  hashes:
    binhash: 2d6c41b66024e460fcfe0a1668bfe151
    md5: b74bf123f1e4557368a61732cf24f1c2
work/INPUT/RYF.tas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.tas.1990_1991.nc
  hashes:
    binhash: 2a7a2f9903346123161b91ed8d5fab52
    md5: 06689885f4f2f726b95a2818ab78a20d
work/INPUT/RYF.uas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.uas.1990_1991.nc
  hashes:
    binhash: bfd4876aac0b31e51a18c7724c84d8b1
    md5: 107bf9480f55597655d2d283b6f6b4ff
work/INPUT/RYF.vas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-4/data/RYF.vas.1990_1991.nc
  hashes:
    binhash: d15ca562e37e82fb2d31657701f0a560
    md5: 88dc8c70338bbc8f5efc48ed0009a99f
work/INPUT/access-om2-1deg-ESMFmesh.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/meshes/global.1deg/2024.01.25/access-om2-1deg-ESMFmesh.nc
  hashes:
    binhash: aa3b7d102b4069d5a5ed9446d857f1a4
    md5: 44e508ac57b244fc357faf5b12933bed
work/INPUT/access-om2-1deg-nomask-ESMFmesh.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/meshes/global.1deg/2024.01.25/access-om2-1deg-nomask-ESMFmesh.nc
  hashes:
    binhash: 4b1cc45032afeaf93b4894937639f5b9
    md5: 9b7120a42b5cb587492e7c31791eb549
work/INPUT/grid.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/cice/grids/global.1deg/2024.05.14/grid.nc
  hashes:
    binhash: b347eb0588291c34bb40a24a7bc45173
    md5: 544a40b634c182f3e182da6bcbe8be7b
work/INPUT/iced.1900-01-01-10800.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/cice/initial_conditions/global.1deg/2023.07.28/iced.1900-01-01-10800.nc
  hashes:
    binhash: 414174d244807698f8c919f763d3d51d
    md5: 87c012d60c58c65bb56caa98779e5e51
work/INPUT/kmt.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/cice/grids/global.1deg/2024.05.14/kmt.nc
  hashes:
    binhash: 670a7fb52cdc440673304d9a775b3dac
    md5: 4dae75252ac93467f10ea26e833e13d2
work/INPUT/ocean_hgrid.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/mom/grids/mosaic/global.1deg/2020.05.30/ocean_hgrid.nc
  hashes:
    binhash: 3526d89ffb639455c6a1218f5139d5b2
    md5: 51f58be0f4ea6da2cb438a893f95c689
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/mom/initial_conditions/global.1deg/2020.10.22/ocean_temp_salt.res.nc
  hashes:
    binhash: efb5e5e124648f2d59d4cd56b6e9a023
    md5: c5f7e60b5427a4442f111adc65a2d067
work/INPUT/ocean_vgrid.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/mom/grids/vertical/global.1deg/2023.07.28/ocean_vgrid.nc
  hashes:
    binhash: ad5bf87f1c69ef3be1061a5c6d1d0411
    md5: a1e0b0b0adc363506ff17a362e83f64a
work/INPUT/salt_sfc_restore.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/mom/surface_salt_restoring/global.1deg/2020.05.30/salt_sfc_restore.nc
  hashes:
    binhash: 425ccc4989dc3e1acdecc6ffd7e9a870
    md5: b2bd35c44017597ba99b85fb61ed4d72
work/INPUT/topog.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/grids/global.1deg/2020.10.22/topog.nc
  hashes:
    binhash: 101cb5069e11e9f3196a5a6804fa0780
    md5: 4e13d88001b646f3cf4f1c3b8db59f91
