format: yamanifest
version: 1.0
---
work/INPUT/JRA55do-datm-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/share/2026.01.21/JRA55do-datm-ESMFmesh.nc
  hashes:
    binhash: c0e9a071f20670930d0e117f13399d78
    md5: 0ecb68f878b91b8adc90838e2c413914
work/INPUT/JRA55do-drof-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/share/2026.01.21/JRA55do-drof-ESMFmesh.nc
  hashes:
    binhash: 9f3ee3ce42e776fcbee8026e0c3880f5
    md5: bf62c4e7786ddfbe56d61b3074d5d16d
work/INPUT/RYF.friver.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.friver.1990_1991.nc
  hashes:
    binhash: 7ed1b4267c202eae4e1e1fb7170adfdc
    md5: 06d549192558fc48c43416b1015044bc
work/INPUT/RYF.huss.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.huss.1990_1991.nc
  hashes:
    binhash: be1a71017ed8b5392505b2b013e05343
    md5: 76bce15820d66e4dbd55674072253869
work/INPUT/RYF.licalvf.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.licalvf.1990_1991.nc
  hashes:
    binhash: e7eb183d2b7cdd685bdee810004cf3c9
    md5: 33aba38d6bffb45f9b1ce6240c2cd21a
work/INPUT/RYF.prra.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.prra.1990_1991.nc
  hashes:
    binhash: 1d8af8b1b94d1cf78a3108477d329d06
    md5: 4e1210fa78c124c1537e8ce28584555c
work/INPUT/RYF.prsn.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.prsn.1990_1991.nc
  hashes:
    binhash: 5b9d401daa0c90298d703a3a2dac12b1
    md5: 1fa60bceab287d4059c6a23d5fb18170
work/INPUT/RYF.psl.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.psl.1990_1991.nc
  hashes:
    binhash: e85798bf489561d1eb316a50b170f318
    md5: 40003042b732f70edaf59f302427b213
work/INPUT/RYF.rlds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.rlds.1990_1991.nc
  hashes:
    binhash: 33502887b018dbb288775102c1411d65
    md5: 449ca4bd2d51794204a6ceedc79bad82
work/INPUT/RYF.rsds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.rsds.1990_1991.nc
  hashes:
    binhash: ca831af4d8931736138d04166910b7c4
    md5: 7d8e5270940eaaf5121b72eea736b2cd
work/INPUT/RYF.tas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.tas.1990_1991.nc
  hashes:
    binhash: ae172b9c06fe1b5b2b0a2b78e7de0d17
    md5: 1947327fb37d4d1e7eee3e1804500721
work/INPUT/RYF.uas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.uas.1990_1991.nc
  hashes:
    binhash: 7271b6b617e233932c5e319a63c64bc3
    md5: 74516d793e148d522b2b2f73eb6eb6c7
work/INPUT/RYF.vas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.vas.1990_1991.nc
  hashes:
    binhash: f353a71a014062723ed2b56353932caf
    md5: 30b92b1e409cff9a9900692aa961aba4
work/INPUT/Yamazaki_ACCESS-OM2_IC_LarsenWeddellRossedits_smoothed.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/Yamazaki_ACCESS-OM2_IC_LarsenWeddellRossedits_smoothed.nc
  hashes:
    binhash: 39ea28d399510f69cb82ac67793cd707
    md5: 4bb7af6ab6b226e08760931cb1748fce
work/INPUT/access-om3-8km-ESMFmesh_Charrassin_nocavity_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/150925/access-om3-8km-ESMFmesh_Charrassin_nocavity_cropped.nc
  hashes:
    binhash: 672dea8da22a7f1fdd97edfe40c44df5
    md5: 7dc01fc3a9c875f93690d6c7528b1b70
work/INPUT/access-om3-8km-nomask-ESMFmesh_Charrassin_nocavity_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/150925/access-om3-8km-nomask-ESMFmesh_Charrassin_nocavity_cropped.nc
  hashes:
    binhash: 6509f14502ad3fafc036877e78bfacbb
    md5: 28d78cf58801f559effb201dc2bf3ec4
work/INPUT/access-om3-8km-rof-remap-weights_Charrassin_nocavity_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/150925/access-om3-8km-rof-remap-weights_Charrassin_nocavity_cropped.nc
  hashes:
    binhash: c9513406900bf21fc9062833c7e420d0
    md5: 38c29881d380d2911fb31bbc1f987391
work/INPUT/bottom_roughness_extended_into_cavity_74Sedit.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/bottom_roughness_extended_into_cavity_74Sedit.nc
  hashes:
    binhash: 9a5e6177396dcce6ae16234fed962bba
    md5: 7f82353f4add21c0694a793d4480e50f
work/INPUT/diag_rho2.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/diag_rho2.nc
  hashes:
    binhash: 36ef1761b629df34ea5443850b2f18b4
    md5: b8abcb148bb3ef71282d6be4531e491e
work/INPUT/forcing_access_yr2_8km_fill_mod.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/forcing_access_yr2_8km_fill_mod.nc
  hashes:
    binhash: cce484e1cea5aaf5a622eea80c376094
    md5: 487153ac346d933eb3a0f1fefd991a8c
work/INPUT/ice_thickness_Charrassin_regridded_cropped_add_area_where_iceelev_noGL5m_ADDHMASKFILLTHICK_150925.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/150925/ice_thickness_Charrassin_regridded_cropped_add_area_where_iceelev_noGL5m_ADDHMASKFILLTHICK_150925.nc
  hashes:
    binhash: 5356f3fee2284a99e18d320190941700
    md5: e3b33e2834ffd0e638f890173e000ce0
work/INPUT/kmt_Charrassin_sea_ice_from_iceelev_new150925.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/150925/kmt_Charrassin_sea_ice_from_iceelev_new150925.nc
  hashes:
    binhash: 2a4220f97a681a1ad4f3f42fb15bc158
    md5: 551a62a9e522b16126bae843e257313f
work/INPUT/mask_table.1490.84x49:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/mask_table.1490.84x49
  hashes:
    binhash: f880529c8f25b89a50bcff8d51574ab0
    md5: 2d21eca0c746628fc47f1c32ea500e11
work/INPUT/ocean_hgrid_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/ocean_hgrid_cropped.nc
  hashes:
    binhash: d33f874bec8aea015ae9de1c08f12f8f
    md5: a1876832e039ca9bf761b8c16a08449e
work/INPUT/ocean_vgrid_cropped.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/ocean_vgrid_cropped.nc
  hashes:
    binhash: d319d71d04eaa91e9fab04dec49893f8
    md5: 66f71f2b24bd00b1c220787505e0106e
work/INPUT/salt_restore_interpolated_nearest.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/salt_restore_interpolated_nearest.nc
  hashes:
    binhash: d73604715b2dc98e71f9b9146d4719b7
    md5: 62bcbd4638b849e1fada4f4e08dc228c
work/INPUT/salt_restore_mask.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/150925/salt_restore_mask.nc
  hashes:
    binhash: 14f469398a2ff3e60c472fd4adfcd090
    md5: 89e3a69b96d12492c0baab68d3bc9b79
work/INPUT/tideamp_Charrassin_cavity_cropped.nc:
  fullpath: /g/data/x77/cy8964/mom6/input/input-8km/tideamp_Charrassin_cavity_cropped.nc
  hashes:
    binhash: 70ee8bead772885e9697a563ea275f4b
    md5: 12af3ec0ed46cdf425dc72f869567dde
work/INPUT/topog_Charrassin_open_cavity_noGL5m_new150925.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/150925/topog_Charrassin_open_cavity_noGL5m_new150925.nc
  hashes:
    binhash: 720de9f6a01a74c20e054b46df225b91
    md5: 18ed8e8bd321b8f4375ece4e9afe2f5f
work/INPUT/topog_Charrassin_sea_ice_from_iceelev_new150925.nc:
  fullpath: /g/data/tm70/cy8964/mom6/input/input-8km/150925/topog_Charrassin_sea_ice_from_iceelev_new150925.nc
  hashes:
    binhash: ef1a91aab4a437721489eb60c944627f
    md5: b6d663421561dd6478744c63216e5b8d
