format: yamanifest
version: 1.0
---
work/INPUT/JRA55do-datm-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/2025.12.12/JRA55do-datm-ESMFmesh.nc
  hashes:
    binhash: 2dc5c84b1ab812b8d9dec4388e5ca3fa
    md5: 218c46d10ac75dae5c322b2bc47c4e3d
work/INPUT/JRA55do-drof-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/2025.12.12/JRA55do-drof-ESMFmesh.nc
  hashes:
    binhash: c25b7e3f03461c533d6638c30e0e3ebd
    md5: 7ec410740252043c5ba9658bbe99cc93
work/INPUT/RYF.friver.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.friver.1990_1991.nc
  hashes:
    binhash: 7ed1b4267c202eae4e1e1fb7170adfdc
    md5: 06d549192558fc48c43416b1015044bc
work/INPUT/RYF.huss.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.huss.1990_1991.nc
  hashes:
    binhash: be1a71017ed8b5392505b2b013e05343
    md5: 76bce15820d66e4dbd55674072253869
work/INPUT/RYF.licalvf.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.licalvf.1990_1991.nc
  hashes:
    binhash: e7eb183d2b7cdd685bdee810004cf3c9
    md5: 33aba38d6bffb45f9b1ce6240c2cd21a
work/INPUT/RYF.prra.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.prra.1990_1991.nc
  hashes:
    binhash: 1d8af8b1b94d1cf78a3108477d329d06
    md5: 4e1210fa78c124c1537e8ce28584555c
work/INPUT/RYF.prsn.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.prsn.1990_1991.nc
  hashes:
    binhash: 5b9d401daa0c90298d703a3a2dac12b1
    md5: 1fa60bceab287d4059c6a23d5fb18170
work/INPUT/RYF.psl.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.psl.1990_1991.nc
  hashes:
    binhash: e85798bf489561d1eb316a50b170f318
    md5: 40003042b732f70edaf59f302427b213
work/INPUT/RYF.rlds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.rlds.1990_1991.nc
  hashes:
    binhash: 33502887b018dbb288775102c1411d65
    md5: 449ca4bd2d51794204a6ceedc79bad82
work/INPUT/RYF.rsds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.rsds.1990_1991.nc
  hashes:
    binhash: ca831af4d8931736138d04166910b7c4
    md5: 7d8e5270940eaaf5121b72eea736b2cd
work/INPUT/RYF.tas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.tas.1990_1991.nc
  hashes:
    binhash: ae172b9c06fe1b5b2b0a2b78e7de0d17
    md5: 1947327fb37d4d1e7eee3e1804500721
work/INPUT/RYF.uas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.uas.1990_1991.nc
  hashes:
    binhash: 7271b6b617e233932c5e319a63c64bc3
    md5: 74516d793e148d522b2b2f73eb6eb6c7
work/INPUT/RYF.vas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.vas.1990_1991.nc
  hashes:
    binhash: f353a71a014062723ed2b56353932caf
    md5: 30b92b1e409cff9a9900692aa961aba4
work/INPUT/access-om2-100km-ESMFmesh.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/meshes/global.100km/2024.01.25/access-om2-100km-ESMFmesh.nc
  hashes:
    binhash: 1ef89b82613d3ef0e903df4aeeb395ce
    md5: 44e508ac57b244fc357faf5b12933bed
work/INPUT/access-om2-100km-nomask-ESMFmesh.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/meshes/global.100km/2024.01.25/access-om2-100km-nomask-ESMFmesh.nc
  hashes:
    binhash: 38605aedd850ec5c9d208258f2030166
    md5: 9b7120a42b5cb587492e7c31791eb549
work/INPUT/bottom_roughness.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/tidal_external_files/global.100km/2025.09.22/bottom_roughness.nc
  hashes:
    binhash: e28f832d8cf239fb52e8a835047c9529
    md5: 014f9b95036b9e5a54a24e3643de675b
work/INPUT/chl_globcolour_monthly_clim.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/chlorophyll/global.100km/2025.11.25/chl_globcolour_monthly_clim.nc
  hashes:
    binhash: 5e580f19cb229602926802917f24312c
    md5: d18a52a5e8c7e67de67e0924580f6a10
work/INPUT/iced.1900-01-01-10800.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/cice/initial_conditions/global.100km/2023.07.28/iced.1900-01-01-10800.nc
  hashes:
    binhash: 414174d244807698f8c919f763d3d51d
    md5: 87c012d60c58c65bb56caa98779e5e51
work/INPUT/kmt.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/cice/grids/global.100km/2024.05.14/kmt.nc
  hashes:
    binhash: 670a7fb52cdc440673304d9a775b3dac
    md5: 4dae75252ac93467f10ea26e833e13d2
work/INPUT/ocean_hgrid.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/mom/grids/mosaic/global.100km/2020.05.30/ocean_hgrid.nc
  hashes:
    binhash: 3526d89ffb639455c6a1218f5139d5b2
    md5: 51f58be0f4ea6da2cb438a893f95c689
work/INPUT/ocean_vgrid.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/grids/vertical/share/2025.03.12/ocean_vgrid.nc
  hashes:
    binhash: 9c1f82b7ea91a8647c8857c02676a7a5
    md5: 66f71f2b24bd00b1c220787505e0106e
work/INPUT/salt_sfc_restore.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/surface_salt_restoring/global.100km/2025.10.24/salt_sfc_restore.nc
  hashes:
    binhash: c1a439bdf28b6a801317e59f6c6d0f3f
    md5: aa31093850132ba8601ae94e74d6b848
work/INPUT/tideamp.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/tidal_external_files/global.100km/2025.09.22/tideamp.nc
  hashes:
    binhash: 10931d9f5303f728e1bf796b8736613a
    md5: 9bcd9d203632a58221a53b3f7ca51622
work/INPUT/topog.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/share/grids/global.100km/2020.10.22/topog.nc
  hashes:
    binhash: 101cb5069e11e9f3196a5a6804fa0780
    md5: 4e13d88001b646f3cf4f1c3b8db59f91
work/INPUT/woa23_ts_01_mom.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/mom/initial_conditions/global.100km/2025.10.24/woa23_ts_01_mom.nc
  hashes:
    binhash: 3187b31900308c4738ae4bb9cd9d3e94
    md5: c6e87eaa93953a8fbe7862fe28f8a546
