format: yamanifest
version: 1.0
---
work/INPUT/JRA55do-datm-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/share/2026.01.21/JRA55do-datm-ESMFmesh.nc
  hashes:
    binhash: c0e9a071f20670930d0e117f13399d78
    md5: 0ecb68f878b91b8adc90838e2c413914
work/INPUT/JRA55do-drof-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/share/meshes/share/2026.01.21/JRA55do-drof-ESMFmesh.nc
  hashes:
    binhash: 9f3ee3ce42e776fcbee8026e0c3880f5
    md5: bf62c4e7786ddfbe56d61b3074d5d16d
work/INPUT/OBC37S_forcing_access_yr2_4km.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/OBC37S_forcing_access_yr2_4km.nc
  hashes:
    binhash: 39b50148464d56adc7845d79189c0208
    md5: 487153ac346d933eb3a0f1fefd991a8c
work/INPUT/RYF.friver.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.friver.1990_1991.nc
  hashes:
    binhash: 7ed1b4267c202eae4e1e1fb7170adfdc
    md5: 06d549192558fc48c43416b1015044bc
work/INPUT/RYF.huss.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.huss.1990_1991.nc
  hashes:
    binhash: be1a71017ed8b5392505b2b013e05343
    md5: 76bce15820d66e4dbd55674072253869
work/INPUT/RYF.licalvf.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.licalvf.1990_1991.nc
  hashes:
    binhash: e7eb183d2b7cdd685bdee810004cf3c9
    md5: 33aba38d6bffb45f9b1ce6240c2cd21a
work/INPUT/RYF.prra.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.prra.1990_1991.nc
  hashes:
    binhash: 1d8af8b1b94d1cf78a3108477d329d06
    md5: 4e1210fa78c124c1537e8ce28584555c
work/INPUT/RYF.prsn.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.prsn.1990_1991.nc
  hashes:
    binhash: 5b9d401daa0c90298d703a3a2dac12b1
    md5: 1fa60bceab287d4059c6a23d5fb18170
work/INPUT/RYF.psl.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.psl.1990_1991.nc
  hashes:
    binhash: e85798bf489561d1eb316a50b170f318
    md5: 40003042b732f70edaf59f302427b213
work/INPUT/RYF.rlds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.rlds.1990_1991.nc
  hashes:
    binhash: 33502887b018dbb288775102c1411d65
    md5: 449ca4bd2d51794204a6ceedc79bad82
work/INPUT/RYF.rsds.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.rsds.1990_1991.nc
  hashes:
    binhash: ca831af4d8931736138d04166910b7c4
    md5: 7d8e5270940eaaf5121b72eea736b2cd
work/INPUT/RYF.tas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.tas.1990_1991.nc
  hashes:
    binhash: ae172b9c06fe1b5b2b0a2b78e7de0d17
    md5: 1947327fb37d4d1e7eee3e1804500721
work/INPUT/RYF.uas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.uas.1990_1991.nc
  hashes:
    binhash: 7271b6b617e233932c5e319a63c64bc3
    md5: 74516d793e148d522b2b2f73eb6eb6c7
work/INPUT/RYF.vas.1990_1991.nc:
  fullpath: /g/data/vk83/configurations/inputs/JRA-55/RYF/v1-6/data/RYF.vas.1990_1991.nc
  hashes:
    binhash: f353a71a014062723ed2b56353932caf
    md5: 30b92b1e409cff9a9900692aa961aba4
work/INPUT/access-om3-4km-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/access-om3-4km-ESMFmesh.nc
  hashes:
    binhash: 83ca4dae88dcaa5f405784c536fc4757
    md5: 7dc01fc3a9c875f93690d6c7528b1b70
work/INPUT/access-om3-4km-nomask-ESMFmesh.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/access-om3-4km-nomask-ESMFmesh.nc
  hashes:
    binhash: 95bde3efc00d398d00c3bb6790f8023b
    md5: 28d78cf58801f559effb201dc2bf3ec4
work/INPUT/access-om3-4km-rof-remap-weights.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/access-om3-4km-rof-remap-weights.nc
  hashes:
    binhash: 0b87e16c64b846abcda73a04841c0b80
    md5: 38c29881d380d2911fb31bbc1f987391
work/INPUT/bottom_roughness.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/bottom_roughness.nc
  hashes:
    binhash: 8a947441b2ee9162af7d4a3030bb4153
    md5: 7f82353f4add21c0694a793d4480e50f
work/INPUT/diag_rho2.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/diag_rho2.nc
  hashes:
    binhash: fab458dc2a1c9fbb9ef0b6420aebaa78
    md5: b8abcb148bb3ef71282d6be4531e491e
work/INPUT/ice_shelf_thick.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/ice_shelf_thick.nc
  hashes:
    binhash: a92ad5eefa1e3b9adf0992d7cebe7c93
    md5: e3b33e2834ffd0e638f890173e000ce0
work/INPUT/kmt.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/kmt.nc
  hashes:
    binhash: 8d34a488332e54be5d932a997c44d9ab
    md5: 551a62a9e522b16126bae843e257313f
work/INPUT/mask_table.1490.84x49:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/mask_table.1490.84x49
  hashes:
    binhash: ad56cbcee4ee95de2389a555f0fe14d5
    md5: 2d21eca0c746628fc47f1c32ea500e11
work/INPUT/ocean_hgrid.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/ocean_hgrid.nc
  hashes:
    binhash: 931f526ede0691b223ca4bb42879eeb3
    md5: a1876832e039ca9bf761b8c16a08449e
work/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/ocean_temp_salt.res.nc
  hashes:
    binhash: 8345a635ab30295f2cd6b3640f591223
    md5: 4bb7af6ab6b226e08760931cb1748fce
work/INPUT/ocean_vgrid.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/ocean_vgrid.nc
  hashes:
    binhash: 55ccd1cf1887ece8c2b5788600f49100
    md5: 66f71f2b24bd00b1c220787505e0106e
work/INPUT/salt_restore_mask.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/salt_restore_mask.nc
  hashes:
    binhash: 5cb019b840db395e08a95c32001f31d9
    md5: 89e3a69b96d12492c0baab68d3bc9b79
work/INPUT/salt_sfc_restore.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan.4km/2026.01.08/salt_sfc_restore.nc
  hashes:
    binhash: 8b43aba8e111b98d2294c4733ea573ab
    md5: 62bcbd4638b849e1fada4f4e08dc228c
work/INPUT/tideamp.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/tideamp.nc
  hashes:
    binhash: 115f80c9b9f0600c76a4c348a89e7d99
    md5: 12af3ec0ed46cdf425dc72f869567dde
work/INPUT/topog.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/topog.nc
  hashes:
    binhash: 4c89085e6ca52f1c41f7c1a2f056a9e6
    md5: 18ed8e8bd321b8f4375ece4e9afe2f5f
work/INPUT/topog_seaice.nc:
  fullpath: /g/data/vk83/prerelease/configurations/inputs/access-om3/panan-isf.4km/2026.01.08/topog_seaice.nc
  hashes:
    binhash: 22d9f7a24ee41e4f0fc024b5d4511c2a
    md5: b6d663421561dd6478744c63216e5b8d
