format: yamanifest
version: 1.0
---
work/Shelf.res.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/Shelf.res.nc
  hashes:
    binhash: b339f6d64efa31c939e4c1c1627d08d4
    md5: 13210a8187af782a25e64219c22f9e05
work/access-om3.cice.r.1905-07-01-00000.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.cice.r.1905-07-01-00000.nc
  hashes:
    binhash: 846ddef2c085b6fa7d0a1f9eabc1c99c
    md5: 09dbc20ce15388b0e5ea7d9a55af295c
work/access-om3.cpl.r.1905-07-01-00000.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.cpl.r.1905-07-01-00000.nc
  hashes:
    binhash: 965c922a6a4a5f812d5827d9c706bc6b
    md5: acb24cf64b4129e32bbfd271454dddd5
work/access-om3.datm.r.1905-07-01-00000.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.datm.r.1905-07-01-00000.nc
  hashes:
    binhash: b8f13903ae7c37ccfcbab03db14dc96c
    md5: 81a56302103745327a30f781ebccda06
work/access-om3.drof.r.1905-07-01-00000.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.drof.r.1905-07-01-00000.nc
  hashes:
    binhash: fa3b89ea9ca33cc07e93edd145416357
    md5: 8ae9777c0e4e9255da7f9dd23047c16f
work/access-om3.mom6.r.1905-07-01-00000.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000.nc
  hashes:
    binhash: 7f2c0dc78f8b09d7a50b7a35e815f7b6
    md5: 562108bc7c8cb75f5ac8c64464cc1aac
work/access-om3.mom6.r.1905-07-01-00000_1.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_1.nc
  hashes:
    binhash: e849727d07adf01d53978ddbe30e6132
    md5: 154054e24f051063c2588c441246cacf
work/access-om3.mom6.r.1905-07-01-00000_10.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_10.nc
  hashes:
    binhash: cfe1a95d4bc241275cc08dec18d26beb
    md5: 00f0ad794f2a05da2c76852f6b8f5198
work/access-om3.mom6.r.1905-07-01-00000_11.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_11.nc
  hashes:
    binhash: 5bc8dbc250291e9442f9de3b0786d84b
    md5: fe8240cf2f8fbdb542ca603b8e18a588
work/access-om3.mom6.r.1905-07-01-00000_12.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_12.nc
  hashes:
    binhash: f36a21c9dd07da42420aa21c402ad90f
    md5: 27211cf5d06b3e6e0f7d5bcc2329ff5b
work/access-om3.mom6.r.1905-07-01-00000_13.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_13.nc
  hashes:
    binhash: 2b25e38a944ba61ae712258e24c92e3a
    md5: 4612b9169eb197307fa0e82d273e3383
work/access-om3.mom6.r.1905-07-01-00000_14.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_14.nc
  hashes:
    binhash: 8deb980abf7cb4932135b18612e3e595
    md5: d852ef4b5260f43772844acdafc61a1a
work/access-om3.mom6.r.1905-07-01-00000_15.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_15.nc
  hashes:
    binhash: d278e1ef74e6e2251d74db585d5a3a96
    md5: 06b380d10a073fe3bddfc17d47c2ca63
work/access-om3.mom6.r.1905-07-01-00000_16.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_16.nc
  hashes:
    binhash: 3593fe558b6d9727731a77491faebb38
    md5: 13cd47a67980276baa8ac7f37ecc3d49
work/access-om3.mom6.r.1905-07-01-00000_17.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_17.nc
  hashes:
    binhash: e84322e1269989c15b8e7e66d12c9a5d
    md5: 5ad1288c91ed6ef33a9996294743971b
work/access-om3.mom6.r.1905-07-01-00000_18.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_18.nc
  hashes:
    binhash: 8f14dc0e12b266adfea66fceef0c3242
    md5: 905409e22cda3078143476e1334e7dcb
work/access-om3.mom6.r.1905-07-01-00000_2.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_2.nc
  hashes:
    binhash: 1ef3ee22a71bfd6136ed90ddf6d223b2
    md5: ad3ed554fc0f124e829bc85d334ec430
work/access-om3.mom6.r.1905-07-01-00000_3.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_3.nc
  hashes:
    binhash: 9900fbf2368c59168456af2f990da268
    md5: 56fa9eba2e2a733ed5e209c98f05b4ae
work/access-om3.mom6.r.1905-07-01-00000_4.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_4.nc
  hashes:
    binhash: 6f40c492d8cd958c5f1958944ccb1f72
    md5: e48c4eddd870980809c4600e9f5cd8f3
work/access-om3.mom6.r.1905-07-01-00000_5.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_5.nc
  hashes:
    binhash: 24097cd975cdf2225315f0038d0e89c8
    md5: 482c56da948d0bc4b3f9525a2fa60fa7
work/access-om3.mom6.r.1905-07-01-00000_6.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_6.nc
  hashes:
    binhash: 541198cb3795d069f14fe9323f42f001
    md5: 6e07badd9e4c4a85a6d84df32bf30876
work/access-om3.mom6.r.1905-07-01-00000_7.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_7.nc
  hashes:
    binhash: fc2ea01b759272fba91652659429d6d8
    md5: 7f4fd0feddef06b399f8a4322682c562
work/access-om3.mom6.r.1905-07-01-00000_8.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_8.nc
  hashes:
    binhash: 8f9d84eaee976cb05bbeb2cf2b8d57cd
    md5: 2b704cb4a0cefc136e3a93947c60ab13
work/access-om3.mom6.r.1905-07-01-00000_9.nc:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/access-om3.mom6.r.1905-07-01-00000_9.nc
  hashes:
    binhash: 513c5fc65f20e387e39480ceff490562
    md5: 4543c5dfb28cac4a4a49762123959aae
work/rpointer.atm:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/rpointer.atm
  hashes:
    binhash: 9bea39543a60e19bd99104854aa7c830
    md5: 18aa92fddd7da7034fe995e4f085a7d9
work/rpointer.cpl:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/rpointer.cpl
  hashes:
    binhash: d19bc479cbd7d23d19e7d00c5a4bb454
    md5: 0f079a8095ac21f727eae619a3e9dbc9
work/rpointer.ice:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/rpointer.ice
  hashes:
    binhash: 3ef24f64f52e78e829e9d96c77e31f63
    md5: 940e5a6c2655f261b8b1ecab9041af39
work/rpointer.ocn:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/rpointer.ocn
  hashes:
    binhash: bb76df934405419a15d90069519e67e0
    md5: dab83041bd010a813f8aa0707c01842d
work/rpointer.rof:
  fullpath: /scratch/x77/cy8964/access-om3/archive/ice_shelf_panan-spin-up-211125/restart065/rpointer.rof
  hashes:
    binhash: b7d9206525458ee6bfd7da47802c1ec6
    md5: b95d1427b35497bc3b0951696ca578a2
